"""'init'

Revision ID: dad021753dec
Revises: 
Create Date: 2023-04-16 01:30:26.646719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad021753dec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_context')
    # ### end Alembic commands ###
